/**
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CoverImage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CoverImage'));
  } else {
    // Browser globals (root is window)
    if (!root.HytaleApi) {
      root.HytaleApi = {};
    }
    root.HytaleApi.Article = factory(root.HytaleApi.ApiClient, root.HytaleApi.CoverImage);
  }
}(this, function(ApiClient, CoverImage) {
  'use strict';




  /**
   * The Article model module.
   * @module model/Article
   * @version 1.0
   */

  /**
   * Constructs a new <code>Article</code>.
   * @alias module:model/Article
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Article</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Article} obj Optional instance to populate.
   * @return {module:model/Article} The populated <code>Article</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('featured')) {
        obj['featured'] = ApiClient.convertToType(data['featured'], 'Boolean');
      }
      if (data.hasOwnProperty('tags')) {
        obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
      }
      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('author')) {
        obj['author'] = ApiClient.convertToType(data['author'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('publishedAt')) {
        obj['publishedAt'] = ApiClient.convertToType(data['publishedAt'], 'String');
      }
      if (data.hasOwnProperty('coverImage')) {
        obj['coverImage'] = CoverImage.constructFromObject(data['coverImage']);
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('publishedTo')) {
        obj['publishedTo'] = ApiClient.convertToType(data['publishedTo'], ['String']);
      }
      if (data.hasOwnProperty('bodyExcerpt')) {
        obj['bodyExcerpt'] = ApiClient.convertToType(data['bodyExcerpt'], 'String');
      }
      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} featured
   */
  exports.prototype['featured'] = undefined;
  /**
   * @member {Array.<String>} tags
   */
  exports.prototype['tags'] = undefined;
  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} author
   */
  exports.prototype['author'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} publishedAt
   */
  exports.prototype['publishedAt'] = undefined;
  /**
   * @member {module:model/CoverImage} coverImage
   */
  exports.prototype['coverImage'] = undefined;
  /**
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * @member {Array.<String>} publishedTo
   */
  exports.prototype['publishedTo'] = undefined;
  /**
   * @member {String} bodyExcerpt
   */
  exports.prototype['bodyExcerpt'] = undefined;
  /**
   * @member {String} body
   */
  exports.prototype['body'] = undefined;



  return exports;
}));


