/**
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HytaleApi) {
      root.HytaleApi = {};
    }
    root.HytaleApi.CoverImage = factory(root.HytaleApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CoverImage model module.
   * @module model/CoverImage
   * @version 1.0
   */

  /**
   * Constructs a new <code>CoverImage</code>.
   * @alias module:model/CoverImage
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>CoverImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CoverImage} obj Optional instance to populate.
   * @return {module:model/CoverImage} The populated <code>CoverImage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('variants')) {
        obj['variants'] = ApiClient.convertToType(data['variants'], ['String']);
      }
      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('s3Key')) {
        obj['s3Key'] = ApiClient.convertToType(data['s3Key'], 'String');
      }
      if (data.hasOwnProperty('mimeType')) {
        obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
      }
      if (data.hasOwnProperty('attached')) {
        obj['attached'] = ApiClient.convertToType(data['attached'], 'Boolean');
      }
      if (data.hasOwnProperty('contentType')) {
        obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
      }
      if (data.hasOwnProperty('contentId')) {
        obj['contentId'] = ApiClient.convertToType(data['contentId'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'String');
      }
      if (data.hasOwnProperty('__v')) {
        obj['__v'] = ApiClient.convertToType(data['__v'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} variants
   */
  exports.prototype['variants'] = undefined;
  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * @member {String} s3Key
   */
  exports.prototype['s3Key'] = undefined;
  /**
   * @member {String} mimeType
   */
  exports.prototype['mimeType'] = undefined;
  /**
   * @member {Boolean} attached
   */
  exports.prototype['attached'] = undefined;
  /**
   * @member {String} contentType
   */
  exports.prototype['contentType'] = undefined;
  /**
   * @member {String} contentId
   */
  exports.prototype['contentId'] = undefined;
  /**
   * @member {String} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * @member {Number} __v
   */
  exports.prototype['__v'] = undefined;



  return exports;
}));


