/**
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HytaleApi);
  }
}(this, function(expect, HytaleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HytaleApi.CoverImage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CoverImage', function() {
    it('should create an instance of CoverImage', function() {
      // uncomment below and update the code to test CoverImage
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be.a(HytaleApi.CoverImage);
    });

    it('should have the property variants (base name: "variants")', function() {
      // uncomment below and update the code to test the property variants
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property s3Key (base name: "s3Key")', function() {
      // uncomment below and update the code to test the property s3Key
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property mimeType (base name: "mimeType")', function() {
      // uncomment below and update the code to test the property mimeType
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property attached (base name: "attached")', function() {
      // uncomment below and update the code to test the property attached
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property contentType (base name: "contentType")', function() {
      // uncomment below and update the code to test the property contentType
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property contentId (base name: "contentId")', function() {
      // uncomment below and update the code to test the property contentId
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

    it('should have the property v (base name: "__v")', function() {
      // uncomment below and update the code to test the property v
      //var instance = new HytaleApi.CoverImage();
      //expect(instance).to.be();
    });

  });

}));
