/**
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HytaleApi);
  }
}(this, function(expect, HytaleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HytaleApi.Job();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Job', function() {
    it('should create an instance of Job', function() {
      // uncomment below and update the code to test Job
      //var instance = new HytaleApi.Job();
      //expect(instance).to.be.a(HytaleApi.Job);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new HytaleApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new HytaleApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property datePosted (base name: "datePosted")', function() {
      // uncomment below and update the code to test the property datePosted
      //var instance = new HytaleApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new HytaleApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property employmentType (base name: "employmentType")', function() {
      // uncomment below and update the code to test the property employmentType
      //var instance = new HytaleApi.Job();
      //expect(instance).to.be();
    });

  });

}));
