/**
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Article', 'model/CoverImage', 'model/Job', 'api/ArticlesApi', 'api/JobsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Article'), require('./model/CoverImage'), require('./model/Job'), require('./api/ArticlesApi'), require('./api/JobsApi'));
  }
}(function(ApiClient, Article, CoverImage, Job, ArticlesApi, JobsApi) {
  'use strict';

  /**
   * Hytale_Official_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var HytaleApi = require('index'); // See note below*.
   * var xxxSvc = new HytaleApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new HytaleApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new HytaleApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new HytaleApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Article model constructor.
     * @property {module:model/Article}
     */
    Article: Article,
    /**
     * The CoverImage model constructor.
     * @property {module:model/CoverImage}
     */
    CoverImage: CoverImage,
    /**
     * The Job model constructor.
     * @property {module:model/Job}
     */
    Job: Job,
    /**
     * The ArticlesApi service constructor.
     * @property {module:api/ArticlesApi}
     */
    ArticlesApi: ArticlesApi,
    /**
     * The JobsApi service constructor.
     * @property {module:api/JobsApi}
     */
    JobsApi: JobsApi
  };

  return exports;
}));
