/**
 * Hytale API
 * Hytale Official API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HytaleApi);
  }
}(this, function(expect, HytaleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HytaleApi.ArticlesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArticlesApi', function() {
    describe('getArticleBySlug', function() {
      it('should call getArticleBySlug successfully', function(done) {
        //uncomment below and update the code to test getArticleBySlug
        //instance.getArticleBySlug(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticles', function() {
      it('should call getArticles successfully', function(done) {
        //uncomment below and update the code to test getArticles
        //instance.getArticles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArticlesOfMonthAndYear', function() {
      it('should call getArticlesOfMonthAndYear successfully', function(done) {
        //uncomment below and update the code to test getArticlesOfMonthAndYear
        //instance.getArticlesOfMonthAndYear(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
